# Generated by Django 4.2.5 on 2023-09-19 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("attendees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendee",
            name="badge",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendee_badge",
                to="attendees.badge",
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="attendee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="badge_attendee",
                serialize=False,
                to="attendees.attendee",
            ),
        ),
    ]
